create database  customer_behavior ;
use    customer_behavior ;
select * from customer;

#1.What is the total rervenue generated by  male vs female customer
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

#2.Which are the top 5  product with the highest average review rating
SELECT `item purchased`, ROUND(AVG(`review rating`), 2) AS avg_rating
FROM customer
GROUP BY `item purchased`
ORDER BY avg_rating DESC
LIMIT 5;

#3.Compare avg purchase amount  between  standard  and express shipping
SELECT `shipping type`, 
ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM customer
WHERE `shipping type` IN ('Standard', 'Express')
GROUP BY `shipping type`;

#4.Do subscribed customers spend more ? compare avg  spend and total revenue between subscribers and non subscribers
SELECT `subscription status`,
ROUND(AVG(purchase_amount), 2) AS avg_spend,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY `subscription status`;

#5.Which 5 products have the highest percentage of purchases eith discount applied
SELECT `item purchased`,
ROUND(SUM(CASE WHEN `discount applied` = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS discount_percentage
FROM customer
GROUP BY `item purchased`
ORDER BY discount_percentage DESC
LIMIT 5;

#6.Which customer used s discount but still spent more than average  purchase amount 
SELECT customer id, purchase_amount
FROM customer
WHERE 'Discount Applied' = "Yes"
AND purchase_amount >= (
    SELECT AVG(purchase_amount)
    FROM customer
);

#7.Who are the top 5 highest spending customers?
SELECT `customer id`, SUM(purchase_amount) AS total_spent
FROM customer
GROUP BY `customer id`
ORDER BY total_spent DESC
LIMIT 5;

#8.Which customers spend more than average?
SELECT `customer id`, purchase_amount
FROM customer
WHERE purchase_amount > (SELECT AVG(purchase_amount) FROM customer
);
#9.Are customers whos are repeat buyers(more than 5 previous purchases) also likely subcribed
SELECT `subscription status`,COUNT(*) AS total_customers
FROM customer
WHERE `previous purchases` > 5
GROUP BY `subscription status`;

#10.What is seasonal revenue trend?
SELECT season, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY season;

#11.Which payment method is most used?
SELECT `payment method`, COUNT(*) AS usage_count
FROM customer
GROUP BY `payment method`
ORDER BY usage_count DESC;

#12.What is average purchase amount by location?
SELECT location, ROUND(AVG(purchase_amount),2) AS avg_spend
FROM customer
GROUP BY location;